version: '2'

services:
    flask:
        image: python:3.6.4
        working_dir: /var/www/flaskrest
        command: bash -c "pip3 install -r requirements.txt && gunicorn --worker-class gevent --bind 0.0.0.0:8099 app:app"
        environment:
            APPNAME: ms-users
            WEB_CONCURRENCY: 3
            PORT: 8099
            API_KEY: 123123123123123123
            DATABASE_URL: postgres://user:pass@host:5432/database
            REDIS_URL: redis://@redis:6379/1
        ports:
            - 8099:8099
        volumes:
            - .:/var/www/flaskrest
        links:
            - "redis:redis"

    redis:
        image: redis
